# fly.toml app configuration file generated for wag-wonders on 2025-01-21T14:16:12+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wag-wonders'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
